title: fooBlog
author: fooMan
email: fooman[dot]in[at]gmail[dot]com
tagline: Learning through sharing
description: > # this means to ignore newlines until "show_exerpts:"
  Here, I share my learning and my thoughts; I write my views on various topics. Sometimes, some guest writers also contribute to this blog.
show_excerpts: true # set to true to show excerpts on the homepage
# baseurl: /texture

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

logo: /assets/images/icons/android-icon-192x192.png

image:
  path: /assets/images/icons/ms-icon-310x310.png
  height: 300
  width: 300

permalink: /posts/:title/
texture:
  title: fooMan
  tagline: Programmer. Reader
  date_format: "%b %-d, %Y"
  style: blue
  showNav: true
  showPicker: false

  # generate social links in post-header
  social_links:
    email: fooman.in@gmail.com
    twitter: ntn_nitz
    # quora:
    # github:  
    # linkedIn: 
    rss: rss
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

url: https://blog.fooman.in

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

collections:
  types:
    output: true
  authors:
    output: true

# Handling Reading
encoding            : "utf-8"
markdown_ext        : "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown            : kramdown

remote_theme: thelehhman/texture
